config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :comments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :memoires do
    member do
      get :download
      get :like
    end
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root 'main#accueil'

  get 'private/admin'

  get 'politics' => 'main#politics'

  get 'termes' => 'main#termes'

  get 'contacts' => 'main#contacts'

  get 'recherche' => 'main#recherche'

  get 'users/:id/memoires' => 'memoires#index', :as => :user_memoires

end

app/controllers/main_controller.rb
## HomePage Controller
class MainController < ApplicationController::MemoiresController

  before_action :set_memoire, only: [:show, :edit, :update, :destroy, :download]
  before_action :authenticate_user!, except: [:download, :index, :show, :accueil, :contacts, :recherche]

  def accueil
    @memoires = Memoire.joins(option: {filiere: :diplome})

    if params[:search]
      @memoires = @memoires.search(params[:search])
    end

    if params[:filieres]
      @memoires = @memoires.where("filieres.id IN (?)", params[:filieres])
    end

    if params[:diplomes]
      @memoires = @memoires.where("diplomes.id IN (?)", params[:diplomes])
    end

    if params[:options]
      @memoires = @memoires.where("options.id IN (?)", params[:options])
    end
    @diplomes = Diplome.all

    @memoires = @memoires.order("updated_at desc").page(params[:page])
  end

  def politics
  end

  def termes
  end

  def contacts
  end

  def accounts
  end

  def recherche
    @memoires = Memoire.joins(option: {filiere: :diplome})

    if params[:search]
      @memoires = @memoires.search(params[:search])
    end

    if params[:filieres]
      @memoires = @memoires.where("filieres.id IN (?)", params[:filieres])
    end

    if params[:diplomes]
      @memoires = @memoires.where("diplomes.id IN (?)", params[:diplomes])
    end

    if params[:options]
      @memoires = @memoires.where("options.id IN (?)", params[:options])
    end

    if params[:annees]
      @memoires = @memoires.where(annee: params[:annees])
    end

    if params[:ecoles]
      @memoires = @memoires.where(ecole: params[:ecoles])
    end

    @memoires = @memoires.page(params[:page])

    @diplomes = Diplome.all
    @filieres = Filiere.all
    @options = Option.all
    @annees = Memoire.group(:annee).count
    @ecoles = Memoire.group(:ecole).count
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_memoire_template.html.erb
<article class="col-md-3 articles">
  <div class="entry-post">
    <div class="entry-sommary">
      <a href="<%=memoire_path(memoire)%>">
        <header class="entry-header"r>
          <div class="entry-meta">
            <span class="entry-date"><%= memoire.option.filiere.diplome.nom %></span>
            <span class="entry-category"> <%= memoire.option.filiere.nom %> / <%= memoire.option.nom %></span>
          </div>
          <h2 class="entry-title wrap-description"><%= link_to "#{memoire.theme}", memoire %></h2>
        </header>
      </a>
    </div>
    <div class="entry-like">
      <%= memoire.created_at.strftime "%d/%m/%Y" %>
      <div class="" style="float: right;">
        <a href="<%= like_memoire_path(memoire) %>" class="like-memo" style="" title="J'aime" data-toggle="tooltip">
          <span class="fa fa-heart like">
            <strong style="color: #543729; font-size: 18px;"><%= memoire.likes.count %></strong>
          </span>
        </a>
      </div>
    </div>
    <div class="entry-meta">
      <span class="entry-name"><%= memoire.auteur %></span>
      <div class="">
        <%= link_to 'Télécharger', download_memoire_path(memoire), :class=> 'btn btn-primary color btn-xs' %>
        <%= link_to 'Lire', memoire, :class=> 'btn btn-success color btn-xs' %>
        <span class="" aria-hidden="true"><%= memoire.view_number %> vues</span>
      </div>
    </div>
  </div>
</article>

app/views/main/accueil.html.erb
<%= render 'layouts/header_content' %>
<%= flash[:alert] %>

<div class="container-fluid">
	<div class="row" id="contenter">
		<!-- <div class="col-md-2" id="filter">
			<div class="">
				<p class="filters">Filtrer</p>
				<%= form_tag root_path, :method => 'get', :class=> "form-margin", id: "mrh" do %>
				<% @diplomes.each_with_index do |diplome, index|%>
				<div class="diplomes panel-group">
					<div class="diplome panel panel-default">
						<div class="panel-heading">
							<a data-toggle="collapse" data-parent="#accordion" href="#diplomes-<%=index%>">
								<span> <%= diplome.nom %> </span>
								(<span class="memoire-number"><%= diplome.count_memoires %></span>)
							</a>
						</div>

						<div class="panel-collapse collapse" id="diplomes-<%=index%>">
							<div class="panel-body">
								<% diplome.filieres.each_with_index do |filiere, index|%>
								<a class="filiere" data-toggle="collapse" data-parent="#accordion" href="#filieres-<%=index%>">
									<span> <%= filiere.nom %> </span>
									(<span class="memoire-number"><%= filiere.count_memoires %></span>)
								</a><br>
								<div class="panel-collapse collapse" id="filieres-<%=index%>">
									<% filiere.options.each do |option|%>
									<p class="option">
										<input type="checkbox" name="options[]" value="<%= option.id %>" id="" class="enquiry">
										<span class="option-name"> <%= option.nom %> </span>
										(<span class="memoire-number"><%= option.count_memoires %></span>)
									</p>
									<% end %>
								</div>
								<% end %>
							</div>
						</div>

					</div>
				</div>
				<% end %>
				<div class="" id="search-memoire">
					<button type="submit" name="button" class="btn btn-lg btn-primary btn-block">Rechercher</button>
				</div>
				<% end %>
			</div>
		</div> -->
		<div class="col-md-12 all-filter">
			<ul class="nav nav-tabs" id="myTab">
				<li class="active"><a href="#home">Plus récents</a></li>
				<li><a href="#votes">Plus votés</a></li>
				<li><a href="#top">Plus populaires</a></li>
			</ul>

			<div class="tab-content">
				<div class="tab-pane active" id="home">
					<% @memoires.each do |memoire| %>
					<%= render partial: 'main/memoire_template', locals: {memoire: memoire}%>
					<% end %>
				</div>
				<div class="tab-pane" id="votes">
					<% Memoire.plus_voter.each do |plus_vote|%>
						<%= render partial: 'main/memoire_template', locals: {memoire: plus_vote}%>
					<% end %>
				</div>

				<div class="tab-pane" id="top">
					<% Memoire.top_memoires.each do |top_memoire| %>
						<%= render partial: 'main/memoire_template', locals: {memoire: top_memoire}%>
					<% end %>
				</div>
			</div>
		</div>
		<div class="paginate-memoires">
			<%= paginate @memoires %>
		</div>
	</div>

	<div class="clearfix"></div>
</div>

<script type="text/javascript">
	$('#myTab a').click(function (e) {
		e.preventDefault();
		$(this).tab('show');
	});
	$('[data-toggle="tooltip"]').tooltip();
</script>

app/views/main/contacts.html.erb
<div class="row" style="background-image: url(assets/map-image.png);">
	<div class="page-padding">
		<div class="col-md-6 col-md-offset-3 page-bottom">
			<h2 class="">Nous contacter</h2>
			<hr style="width: 200px;" class="page-bottom">
			<h4 class="page-bottom">
				Pour toutes vos inquiétudes merci de remplir le formulire ci-dessous.
			</h4>
	    <form action="MAILTO:memoire.contacts@gmail.com" method="post" enctype="text/plain">
	      <div class="row">
	        <div class="form-group col-md-12">
						<label for="nom">Nom Complet</label>
						<input type="text" name="nom" value="" class="form-control" required placeholder="Votre nom et prénom" value="Votre nom Complet"
						  oninvalid="setCustomValidity('Veuillez saisir votre nom svp')" onchange="try{setCustomValidity('')}catch(e){}">
	        </div>
	        <div class="form-group col-md-12">
						<label for="email">Email</label>
						<input type="email" name="email" value="" class="form-control" required placeholder="Votre adresse email">
	        </div>
					<div class="form-group col-md-12">
	          <label for="message">Votre message</label>
						<textarea name="message" rows="8" cols="40" class="form-control" required placeholder="Votre message ou votre inquiétude ici." value="Votre message"
							oninvalid="setCustomValidity('Veuillez saisir votre message svp')" onchange="try{setCustomValidity('')}catch(e){}"></textarea>
	        </div>
	        <div class="form-group col-md-12">
						<input type="submit" name="name" value="Envoyer" class="btn btn-custom btn-block btn-lg">
	        </div>
	      </div>
			</form>
	  </div>
	</div>
</div>

app/views/main/politics.html.erb
<!-- <%= render "layouts/header" %> -->
<h1>Termes de service</h1>
<section class="container">
  At Emploisite.com, we want to ensure that you understand what information we gather about you, how we use it, and the safeguards we have in place in order to protect it. If you have additional questions or would like further information on this topic, please feel free to write to us at support@outsource.com. This privacy policy applies to information collected through this website for both clients and freelancers. Outsource.com may update this policy from time to time. Please check our policy periodically for changes. Your use of this website, and any disputes arising from it, is subject to this privacy policy as well as our Terms of Service and all of its dispute resolution provisions including arbitration, limitation on damages and choice of law.

  1. Type of Information Collected

  We may collect personally identifiable information("PII" - for example, your full name, email address, mailing address, and telephone number) from you when you voluntarily submitting the information while purchasing the items from us. We need this information in order to process and fulfill your order and to notify you of your order status, in order to register you as a user of this site or to provide you with services. We may also collect PII from you if you choose to subscribe to our email program, or participate in sweepstakes, contests, and surveys, or in connection with content or suggestions you post on this site.

  We also collect non-personally identifiable information ("Non-PII" - for example, interests, hobbies, lifestyle choices, groups with whom you are affiliated) from you when you choose to provide or post non-PII information on this website.

  Non-PII may also be collected from you by means of Cookies and Pixel Tags. Cookies are small bits of information that this website places on your computer. We and our third party service providers use cookies and Pixel Tags to identify your IP address, browser type, domain name, and specific web pages through which you click. This data is collected automatically and utilized to help us look for trends to improve our website and your interactive experience. The cookies allow us to recognize you when you return to the website and to provide you with a customized experience that we feel will be of value to you. The cookies that are configured by this website do not contain any personally identifying information, such as your name, or sensitive information, such as your credit card number. Additional information regarding browser cookies and how to disable them is described below.

  Information Collected Upon Registration. If you desire to have access to certain restricted sections of the Website, you will be required to become a registered user, and to submit certain personally identifiable information to Outsource.com. This happens in a number of instances, such as when you sign up for the Outsource.com service, if you desire to receive marketing materials and information, if you submit a Service Request, and/or if you create a Vendor Profile to offer services through Outsource.com. Personally identifiable information that we may collect in such instances may include your full name, password, email address, street address, telephone number, photographs you upload, and other information that you decide to provide us with, or that you decide to include in your public profile.

  Company Information. If you create a Freelancer Profile, you have the opportunity to provide additional information ("Company Information") such as your company name, address, phone number, website and a description of your company and the services you provide. You may also upload a profile picture and portfolio of your previous work. We may supplement or modify the Company Information to conform to our editorial policies or to add information from your website, materials that you supply to us, or publicly available sources. When you respond to a Consumer's Job Request, your Company Information and Profile is displayed to the Consumer making such a Job Request. Providing additional information beyond what is required at registration is entirely optional, but may enable you market your services more effectively and potentially win more jobs at Outsource.com. If you contact us by email through Outsource.com, we may keep a record of your contact information and correspondence, and use such information to respond to your inquiry.

  2. Use of Information Collected

  In general, we may use information that we collect about you to:

  provide you with the products and services that you have requested;
  market your services to potential customers;
  manage your account and provide customer support;
  perform research and analysis about your use of, or interest in, our products, services, or content, or products, services or content offered by others;
  communicate with you by email, postal mail, telephone and/or mobile devices or send newsletters about products or services that may be of interest to you;
  communicate with you with regard to service requests;
  develop and display content and advertising tailored to your interests on our site and other sites;
  verify your eligibility and deliver prizes in connection with contests and sweepstakes;
  enforce our terms and conditions;
  manage our business; and
  perform functions as otherwise described to you at the time of collection.
  In addition, we may use your contact information to market to you, and provide you with information about, our products and services, including but not limited to our service. If you decide at any time that you no longer wish to receive such information or communications from us, please follow the unsubscribe instructions provided in any of the communications.
  Regarding Phone Numbers Collected. Outsource.com may collect users' phone numbers during registration with the sole purpose to connect them with the clients they are in need of and have requested to be connected with. This phone number will not be given or sold to any third-parties who are not on Outsource.com.

  3. Information Sharing and Disclosure

  We want you to understand when and with whom we may share personal or other information we have collected about you or your activities on our web site or while using our services. We do not share personal information with others except as indicated below or when we inform you and give you an opportunity to opt out of having your personal information shared. Under no circumstances, other than in the event of a Business Transfer (as discussed below) will Outsource.com sell, rent, or lease its User lists (or the User list of any individual Service Provider) to a third party. Circumstance under which we may share your personal information:

  To Provide Information to other users. We may share your personal information with users registered with Outsource.com that perform certain services. Sharing this information with users allows you to be accurately matched. The information we share is generally the information requested during registration, including the Client’s first name and last initial, the type of work needed, when the work should be performed, a description of the work needed, and a general budget.

  To Provide Information to Clients. If you are a registered Freelancer, we may share your company information with Clients requesting services through Outsource.com. Sharing this information with Clients helps them to assess Freelancer quality and choose to connect with the Freelancer. The information we share is the information provided in your Freelancer Profile and any information sent in a quote and/or message to the Client.

  To Provide Information to Partner Companies. We may enter into agreements with one or more partner companies pursuant to which we provide a partner company with a URL and a user registration page co-branded with, or private labeled by, the partner company, and the partner company distributes and promotes the URL to its customers. A partner company may want to access personally identifiable information that we collect from its customers. As a result, if you register on Outsource.com through a partner company, or if you are directed to or access Oursource.com or Outsource.com features (such as but not limited to an embedded widget) through a partner company, we may provide your personally identifiable information to the partner company. Because we do not control the privacy practices of our partner company, you should read and understand its privacy policies.

  To Facilitate Outsource.com's Use of Third-Party Services. We engage certain trusted third parties to perform functions and provide services to us, including, without limitation, hosting and maintenance, customer relationship, database storage and management, direct marketing campaigns and User credit card information storage. We will share your personally identifiable information with these third parties, but only to the extent necessary to perform these functions and provide such services, and only pursuant to binding contractual obligations requiring such third parties to maintain the privacy and security of your data.

  To Comply with Laws and Law Enforcement. Outsource.com may provide information to regulatory authorities and law enforcement officials in accordance with applicable law or when we otherwise believe in good faith that the law requires it. There may be instances when we may access or disclose your information in order to protect or defend the legal rights or property Outsource.com

  In Connection with Business Transfers. Outsource.com may sell, transfer or otherwise share some or all of its assets in connection with a merger, reorganization or sale of assets, or in the event of bankruptcy. In such an event, personal information may be one of the assets transferred.

  To Solicit or Provide Advice on Service Provider Selection. Outsource.com, with your explicit opt-in, may publish a message to your Facebook Wall notifying your friends of your use of the Website and soliciting their advice on which service provider to select for your job. In addition, with your explicit opt-in, Outsource.com may publish a message to your Facebook Wall if you provide input, recommendations, or advice on another s service provider selection.

  4. Security

  Outsource.com is very concerned about safeguarding the confidentiality of your personally identifiable information. We employ administrative, physical and electronic measures designed to protect your information from unauthorized access. However, we cannot guarantee that hackers or unauthorized personnel will not gain access to your personal information despite our efforts. You should note that in using Outsource.com, your information would travel through third party infrastructures, which are not under our control.

  5. Links to Other Websites

  Outsource.com may contain links to other websites. Outsource.com is not responsible for the privacy practices of other websites. Outsource.com users should read the privacy statements of each and every website that collects personally identifiable information.

  6. Regarding Children

  This website is a general audience site and does not knowingly collect personally identifiable information from children under 13 years of age. If Outsource.com becomes aware that a child under 13 has submitted personally identifiable information, Outsource.com will delete that information. Parents who become aware that a child under the age of 13 has submitted personal information to Outsource.com may contact us at support@outsource.com.

  7. Changing or Deleting Information

  If you are a registered user of Outsource.com, you may access and update or correct the information you provided to us by updating your settings in Account Information. If you wish to delete your account, you must email us at support@outsource.com or call us at (866) 784-1265.
</section>
<!-- <%= render "layouts/footer" %> -->

app/views/main/recherche.html.erb
<%= render 'layouts/search_header' %>
<%= flash[:alert] %>

<div class="container-fluid">
	<div class="row" id="filts">
		<div class="col-md-12">
			<div class="col-md-2" id="filter0">
				<div class="">
					<a data-toggle="collapse" data-parent="#accordion" href=".tt0">
						<p class="filters">Diplômes</p>
					</a>
					<%= form_tag recherche_path, :method => 'get', :class=> "", id: "search-filts" do %>
						<div class="toto">
							<% @diplomes.each_with_index do |diplome, index|%>
								<div class="panel-collapse collapse tt0">
									<div class="diplomes">
										<span>
											<input type="checkbox" name="diplomes[]" value="<%= diplome.id %>" id="" class="enquiry">
											<span> <%= diplome.nom %> </span>
											(<span class="memoire-number"><%= diplome.count_memoires %></span>)
										</span>
									</div>
								</div>
							<% end %>
						</div>
				</div>
			</div>
			<div class="col-md-2" id="filter1">
				<div class="">
					<a data-toggle="collapse" data-parent="#accordion" href=".tt1">
						<p class="filters">Filières</p>
					</a>
					<div class="toto">
						<% @filieres.each_with_index do |filiere, index|%>
							<div class="panel-collapse collapse tt1">
								<div class="diplomes">
									<span>
										<input type="checkbox" name="filieres[]" value="<%= filiere.id %>" id="" class="enquiry" />
										<span> <%= filiere.nom %> </span>
										(<span class="memoire-number"><%= filiere.count_memoires %></span>)
									</span>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
			<div class="col-md-2" id="filter2">
				<div class="">
					<a data-toggle="collapse" data-parent="#accordion" href=".tt2">
						<p class="filters">Options</p>
					</a>
						<div class="toto">
							<% @options.each_with_index do |option, index|%>
								<div class="panel-collapse collapse tt2">
									<div class="diplomes">
										<span>
											<input type="checkbox" name="options[]" value="<%= option.id %>" id="" class="enquiry">
											<span> <%= option.nom %> </span>
											(<span class="memoire-number"><%= option.count_memoires %></span>)
										</span>
									</div>
								</div>
							<% end %>
						</div>
				</div>
			</div>
			<div class="col-md-2" id="filter3">
				<div class="">
					<a data-toggle="collapse" data-parent="#accordion" href=".tt3">
						<p class="filters">Années</p>
					</a>
						<div class="toto">
							<% @annees.each do |annee|%>
								<div class="panel-collapse collapse tt3">
									<div class="diplomes">
										<span>
											<input type="checkbox" name="annees[]" value="<%= annee[0] %>" id="" class="enquiry">
											<span> <%= annee[0] %> </span>
											(<span class="memoire-number"><%= annee[1] %></span>)
										</span>
									</div>
								</div>
							<% end %>
						</div>
				</div>
			</div>
			<div class="col-md-3" id="filter4">
				<div class="">
					<a data-toggle="collapse" data-parent="#accordion" href=".tt4">
						<p class="filters">Universités</p>
					</a>
						<div class="toto">
							<% @ecoles.each do |ecole|%>
								<div class="panel-collapse collapse tt4">
									<div class="diplomes">
										<span>
											<input type="checkbox" name="ecoles[]" value="<%= ecole[0] %>" id="" class="enquiry">
											<span> <%= ecole[0] %> </span>
											(<span class="memoire-number"><%= ecole[1] %></span>)
										</span>
									</div>
								</div>
							<% end %>
						</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 all-filter">
			<ul class="nav nav-tabs" id="myTab">
				<li class="active"><a href="#home">Plus récents</a></li>
				<li><a href="#votes">Plus votés</a></li>
				<li><a href="#top">Plus populaires</a></li>
			</ul>

			<div class="tab-content">
				<div class="tab-pane active" id="home">
					<% @memoires.each do |memoire| %>
					<%= render partial: 'main/memoire_template', locals: {memoire: memoire}%>
					<% end %>
				</div>
				<div class="tab-pane" id="votes">
					<% Memoire.plus_voter.each do |plus_vote|%>
						<%= render partial: 'main/memoire_template', locals: {memoire: plus_vote}%>
					<% end %>
				</div>

				<div class="tab-pane" id="top">
					<% Memoire.top_memoires.each do |top_memoire| %>
						<%= render partial: 'main/memoire_template', locals: {memoire: top_memoire}%>
					<% end %>
				</div>
			</div>
		</div>
		<div class="paginate-memoires">
			<%= paginate @memoires %>
		</div>
	</div>

	<div class="clearfix"></div>
</div>

<script type="text/javascript">
	$('#myTab a').click(function (e) {
		e.preventDefault();
		$(this).tab('show');
	});
	$('[data-toggle="tooltip"]').tooltip();

	var t = $('input.enquiry');
	t.click( function(e) {
		$('#search-filts').submit();
	});


</script>