config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :comments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :memoires do
    member do
      get :download
      get :like
    end
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root 'main#accueil'

  get 'private/admin'

  get 'politics' => 'main#politics'

  get 'termes' => 'main#termes'

  get 'contacts' => 'main#contacts'

  get 'recherche' => 'main#recherche'

  get 'users/:id/memoires' => 'memoires#index', :as => :user_memoires

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :memoire
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_memoire, only: [:show, :edit, :update, :destroy, :download]
  before_action :authenticate_user!, except: [:download, :index, :show]

  def create
    @memoire = Memoire.find(params[:memoire_id])
    @comment = @memoire.comments.create(body: params[:comment][:body], user_id: current_user.id)
    respond_to do |format|
      if @comment
        format.html { redirect_to @memoire, notice: 'Votre commentaire a été enrégistré avec succès !' }
        format.json { render text: @comment.body, status: :created, location: @comment }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
<strong class="comment-time">Il y a <%= time_ago_in_words(comment.created_at) %></strong><br>
  <p class="comment-text">
    <strong style="color: #8a6d3b;"><%= h(comment.user.nom) %> <%= h(comment.user.prenom) %>:</strong> <%= h(comment.body) %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Author</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.author %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>