config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :comments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :memoires do
    member do
      get :download
      get :like
    end
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root 'main#accueil'

  get 'private/admin'

  get 'politics' => 'main#politics'

  get 'termes' => 'main#termes'

  get 'contacts' => 'main#contacts'

  get 'recherche' => 'main#recherche'

  get 'users/:id/memoires' => 'memoires#index', :as => :user_memoires

end

app/models/memoire.rb
class Memoire < ActiveRecord::Base
  include PgSearch

  belongs_to :user
  has_many :comments
  has_many :likes
  belongs_to :option

  pg_search_scope :search, :against => [:theme, :auteur, :annee, :ecole, :binome]
  paginates_per 9
  has_attached_file :fichier,
   :default_style => :thumb,
   :url => "/:class/:id/:basename.:extension",
   :path => ":rails_root/public/:class/:id/:basename.:extension"

  validates_attachment :fichier, content_type: { content_type: "application/pdf" }

  scope :top_memoires, -> { order(view_number: :desc).limit(6) }

  scope :plus_voter, -> { joins(:likes).order("count_like DESC").select('memoires.*, COUNT(likes.id) AS count_like').group("memoires.id").limit(6) }
end

app/controllers/memoires_controller.rb
## Memoires controller:
class MemoiresController < ApplicationController
  before_action :set_memoire, only: [:show, :edit, :update, :destroy, :download]
  before_action :authenticate_user!, except: [:download, :index, :show]

  def index
    if params[:search]
      @memoires = Memoire.search(params[:search]).page(params[:page]).order("updated_at desc")
    else
      @memoires = current_user.memoires.page(params[:page]).order('updated_at desc')
    end
  end

  def show
    @memoire = Memoire.find(params[:id])
    if @memoire.user_id.present?
      @count = @memoire.update_attribute("view_number", @memoire.view_number + 1)
      @memoire.save
    else
      flash[:error] = 'Désolé! Ce mémoire a été supprimé par son auteur !'
      redirect_to root_path
    end
  end

  def new
    @memoire = Memoire.new
  end

  def edit
    authorize! :update, @memoire
  end

  def create
    @memoire = Memoire.new(memoire_params)
    @memoire.user_id = current_user.id
    options = {
      icon_url: "#{ENV['APP_URL']}/scuilt_cask.png",
      username: 'Scuilt',
      channel: '#memoires'
    }
    @slack_poster = Slack::Poster.new('https://hooks.slack.com/services/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', options)

    respond_to do |format|
      if @memoire.save
        @slack_poster.send_message("Un nouveau theme: #{@memoire.theme} sur Scuilt par #{@memoire.user.email}")
        format.html { redirect_to @memoire, notice: 'Mémoire créé avec succès' }
        format.json { render :show, status: :created, location: @memoire }
      else
        format.html { render :new }
        format.json { render json: @memoire.errors, status: :unprocessable_entity }
      end
    end
  end

  def download
    send_file @memoire.fichier.path, :type => 'application/pdf'
    flash[:notice] = "Votre éléchargement est en cours !"
  end

  def update
    respond_to do |format|
      if @memoire.update(memoire_params)
        format.html { redirect_to @memoire, notice: 'Votre mémorie a été modifié avec succès !' }
        format.json { render :show, status: :ok, location: @memoire }
      else
        format.html { render :edit }
        format.json { render json: @memoire.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @memoire.destroy
    respond_to do |format|
      format.html { redirect_to memoires_url, notice: 'Votre mémorie a été suprimé avec succès !' }
      format.json { head :no_content }
    end
  end

  def like
    @memoire = Memoire.find(params[:id])
    begin
      @like = @memoire.likes.create(user_id: current_user.id, memoire_id: @memoire.id)
      flash[:success] = 'Votre vôte a été pris en compte !'
    rescue
      flash[:error] = 'Désolé! Vous aviez déjà voté pour ce mémoire.'
    end
    redirect_to root_path
  end

  private

    def set_memoire
      @memoire = Memoire.find(params[:id])
    end

    def memoire_params
      params.require(:memoire).permit(:theme, :auteur, :annee, :maitre, :fichier,:binome, :ecole, :option_id, :diplome_id)
    end
end

app/helpers/memoires_helper.rb
module MemoiresHelper
end

app/views/memoires/_edit_form.html.erb
<div class="page-padding">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@memoire) do |f| %>
        <h2 style="font-weight: 200;">Éditer votre mémoire.</h2>
        <hr>
        <% if @memoire.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@memoire.errors.count, "error") %> prohibited this memoire from being saved:</h2>
            <ul>
              <% @memoire.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="form-group col-md-6">
            <%= f.label :thème %>
            <%= f.text_field :theme, :required => true, class: 'form-control' %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :binome, "Le nom de votre binome" %> (<small>Facultatif</small>)
            <%= f.text_field :binome, class: 'form-control' %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :auteur %>
            <%= f.text_field :auteur, :required => true, class: 'form-control' %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :École %>
            <%= f.text_field :ecole, :required => true, class: 'form-control' %>
          </div>

          <div class="form-group col-md-6">
            <%= label_tag :option, 'Sélectionner un dipôme' %>
            <%= f.select(:option_id) do %>
              <% options_array = Option.all.map { |option| ["#{option.filiere.diplome.nom} / #{option.filiere.nom} / #{option.nom}", option.id] } %>
              <%= options_for_select(options_array) %>
            <% end %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :Année %>
            <%= f.select(:annee, [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020], {}, :class => 'form-control')%>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :maitre, "Encadreur" %> (<small>Le nom de votre maitre mémoire</small>)
            <%= f.text_field :maitre, required: true, class: 'form-control'%>
          </div>

          <div class="f">
            <%= f.hidden_field :email, required: true, class: 'form-control', value: current_user.email%>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :fichier %>
            <%= f.file_field :fichier, :required => true, class: 'form-control' %>
          </div>

          <div class="form-group col-md-12">
            <%= f.submit 'Enregistrer', class: 'btn btn-primary btn-lg' %>
          </div>

        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/memoires/_form.html.erb
<div class="page-padding">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@memoire) do |f| %>
        <h2 style="font-weight: 200;">Créer un nouveau mémoire.</h2>
        <hr>
          <% if @memoire.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@memoire.errors.count, "error") %> prohibited this memoire from being saved:</h2>
              <ul>
                <% @memoire.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="form-group col-md-6">
              <%= f.label :thème %>
              <%= f.text_field :theme, :required => true, class: 'form-control' %>
            </div>

            <div class="form-group col-md-6">
              <%= f.label :binome, "Le nom de votre binome" %> (<small>Facultatif</small>)
              <%= f.text_field :binome, class: 'form-control' %>
            </div>

            <div class="form-group col-md-6">
              <%= f.label :auteur %>
              <%= f.text_field :auteur, :required => true, class: 'form-control' %>
            </div>

            <div class="form-group col-md-6">
              <%= f.label :Université %>
              <%= f.text_field :ecole, :required => true, class: 'form-control' %>
            </div>

            <div class="form-group col-md-6">
              <%= label_tag :option, 'Sélectionner un dipôme' %>
              <%= f.select(:option_id, nil, {}, {class: "form-control"}) do %>
                <% options_array = Option.all.map { |option| ["#{option.filiere.diplome.nom} / #{option.filiere.nom} / #{option.nom}", option.id] } %>
                <%= options_for_select(options_array) %>
              <% end %>
            </div>

            <div class="form-group col-md-6">
              <%= f.label :Année %>
              <%= f.select(:annee, [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020], {}, :class => 'form-control')%>
            </div>

            <div class="form-group col-md-6">
              <%= f.label :maitre, "Encadreur" %> (<small>Le nom de votre maitre mémoire</small>)
              <%= f.text_field :maitre, required: true, class: 'form-control'%>
            </div>

            <div class="f">
              <%= f.hidden_field :email, required: true, class: 'form-control' %>
            </div>

            <div class="form-group col-md-6">
              <%= f.label :fichier %>
              <%= f.file_field :fichier, :required => true, class: 'form-control' %>
            </div>

            <div class="form-group col-md-12">
              <%= f.submit 'Publier', class: 'btn btn-primary btn-lg' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/memoires/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-md-offsert-1">
      <%= link_to '<i class="fa fa-angle-left"></i> Retour'.html_safe, memoires_path, class: "btn btn-custom page-margin" %>
    </div>
  </div>
</div>
<%= render 'edit_form' %>

app/views/memoires/index.html.erb
<div class="container-fluid">
  <div class="curuser-mem-title">
    <h1>Mes mémoires</h1>
  </div>
  <div class="col-md-12">
    <div class="header">
        <%= form_tag memoires_path, :method => 'get', class: "form-inline text-right search-form" do %>
          <div class="form-group has-feedback">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Saisir un mot clé" %>
            <span class="fa fa-search form-control-feedback"></span>
          </div>
        <% end %>
        <%= link_to new_memoire_path, class: 'btn btn-primary curuser-new-mem' do %>
          <i class="fa fa-plus-circle"></i> Nouveau mémoire
        <% end %>
      </div>
    <div class="" style="margin-top:50px;">
      <% @memoires.each do |memoire| %>
        <article class="col-md-3 articles">
          <div class="entry-post">
            <div class="entry-sommary">
              <header class="entry-header"r>
                <div class="entry-meta">
                  <span class="entry-date"><%= memoire.option.filiere.diplome.nom %></span>
                  <span class="entry-category"> <%= memoire.option.filiere.nom %> / <%= memoire.option.nom %></span>
                </div>
                <h2 class="entry-title"><%= link_to "#{memoire.theme}", memoire %></h2>
              </header>
             </div>
            <div class="entry-like">
              <%= memoire.created_at.strftime "%d/%m/%Y" %>
              <div class="" style="float: right;">
                <a href="<%= like_memoire_path(memoire) %>" class="" style="" title="J'aime" data-toggle="tooltip">
                  <span class="fa fa-heart like">
                    <strong style="color: #543729; font-size: 18px;"><%= memoire.likes.count %></strong>
                  </span>
                </a>
              </div>
            </div>
            <div class="entry-meta">
              <%= link_to 'Télécharger', download_memoire_path(memoire), :class=> 'btn btn-primary color btn-xs' %>
              <%= link_to 'Lire'.html_safe, memoire, :class=> 'btn btn-success color btn-xs' %>
              <% if can? :update, memoire %>
                <%= link_to 'Modifier'.html_safe, edit_memoire_path(memoire), :class=> 'btn btn-warning color btn-xs' %>
                <%= link_to '<i class="fa fa-trash"></i>'.html_safe, memoire, method: :delete, data: { confirm: 'En êtes-vous sûr de vouloir supprimer ce mémoire ?' }, :class=> 'btn btn-danger color btn-xs' %>
              <% end %>
              <span class="" aria-hidden="true"><%= memoire.view_number %> vues</span>
            </div>
          </div>
        </article>
      <% end %>
    </div>

    <div class="paginate-curuser-mem">
      <%= paginate @memoires %>
    </div>
  </div>
</div>

<script type="text/javascript">

	$('#myTab a').click(function (e) {
		e.preventDefault();
		$(this).tab('show');
	});

	$('[data-toggle="tooltip"]').tooltip();

	$(document).ready(ready);
	$(document).on("page:load", ready);

</script>

app/views/memoires/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-md-offsert-1">
      <%= link_to '<i class="fa fa-angle-left"></i> Retour'.html_safe, memoires_path, class: "btn btn-custom page-margin" %>
    </div>
  </div>
</div>
<%= render 'form' %>

app/views/memoires/show.html.erb
<div class="" id="read">
    <div class="col-md-12">
      <div class="title-bottom">
        <h2 class="theme-title">Thème: <%= @memoire.theme %></h2>
      </div>
    </div>

      <div class="row">
        <div class="col-md-9">
          <div class="content">
            <iframe src="/pdfjs/web/viewer.html?file=<%= @memoire.fichier.url %>" style="border: 0" width="100%" height="1000"></iframe></br>
          </div>
        </div>
        <div class="col-md-3 memoire-desc">
          <%= render "layouts/memoires/infos" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <%= simple_form_for [@memoire, Comment.new] do |f| %>
            <p>
              <%= f.input :body, :label => "Laisser un commentaire", as: :text, input_html: {rows: "3"} %>
            </p>
            <p>
              <%= f.submit :Commenter, :label => "Add Comment", class: "btn btn-primary" %>
            </p>
          <% end %>
          <h3 class="comment-list">Liste des commentaires</h3>
          <div class="" id="comments">
            <%= render partial: @memoire.comments %>
          </div>
        </div>
      </div>
</div>