config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :comments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :memoires do
    member do
      get :download
      get :like
    end
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root 'main#accueil'

  get 'private/admin'

  get 'politics' => 'main#politics'

  get 'termes' => 'main#termes'

  get 'contacts' => 'main#contacts'

  get 'recherche' => 'main#recherche'

  get 'users/:id/memoires' => 'memoires#index', :as => :user_memoires

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div id="foot">
    <div class="row">
      <div class="col-sm-6 col-md-6">
        <p class="copy">&copy; 2016 <a href="http://www.scuilt.com" class="text-danger">Scuilt</a>. Tous drois réservés. <%= link_to "Contact", new_contact_path, :class=>'nav-menu-items' %></p>
      </div>
      <div class="col-sm-6 col-md-3 col-md-offset-2">
        <%if user_signed_in? %>
          <%= link_to "Publier un mémoire", new_memoire_path, class: 'btn btn-custom btn-sm', style: 'margin-top: 10px;' %>
        <%else%>
          <%= link_to "Publier un mémoire", new_user_session_path, class: 'btn btn-custom btn-sm', style: 'margin-top: 10px;' %>
        <%end%>
        <ul class="socials">
          <li class="facebook">
            <a href="https://www.facebook.com/MemoireApp" style="color: #fff !important;" class="facebook" target="_blank">
                <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="twitter">
            <a href="https://twitter.com/memoireapp" style="color: #fff !important;" class="twitter" target="_blank">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="google">
            <a href="https://plus.google.com/u/1/" style="color: #fff !important;" class="google" target="_blank">
              <i class="fa fa-google"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default header">
  <nav>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <span class="navbar-brand"><%= image_tag("scuilt.png", :alt => "", class: "logo") %></span>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  	  <ul class="nav navbar-nav navbar-right">
  	    <% if user_signed_in? %>
          <ul class="nav navbar-nav main-menu">
            <li class="<%= 'active' if current_page?(recherche_path) %>"><%= link_to "Recherche avancée", recherche_path, :class=>'nav-menu-items' %></li>
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Mémoires disponibles", root_path, :class=>'nav-menu-items' %></li>
            <li class="<%= 'active' if current_page?(memoires_path) %>"><%= link_to "Mes mémoires", memoires_path, :class=>'nav-menu-items' %></li>
            <li class="<%= 'active' if current_page?(new_memoire_path) %>"><%= link_to "Publier un mémoire", new_memoire_path, :class=>'nav-menu-items' %></li>
          </ul>
  	      <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%=current_user.email%><b class="caret"></b>
            </a>
  	        <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Paramètres", new_user_password_path(:user) %></li>
              <li><%= link_to "Déconnexion", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <ul class="nav navbar-nav main-menu">
            <li class="<%= 'active' if current_page?(recherche_path) %>"><%= link_to "Recherche avancée", recherche_path, :class=>'nav-menu-items' %></li>
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Mémoires disponibles", root_path, :class=>'nav-menu-items' %></li>
          </ul>
        <% end %>
  	  </ul>
    </div>
  </nav>
</header>

app/views/layouts/_header_content.html.erb
<div class="header-content">
  <div class="container">
    <div id="container">
      <div class="row">
        <h1 class="welcome-note-1">Partagez facilement et simplement vos mémoires</h1>
        <h2 class="welcome-note-2">
          Vous possédez un mémoire et vous aimeriez le publier mais vous ne connaissez pas la procédure à suivre ?
          Scuilt est là pour vous guider. Très simple, rapide et gratuit.
        </h2>
      </div>

        <div class="row search-input">
          <div class="col-md-6 col-md-offset-5">
            <%if user_signed_in? %>
              <%= link_to "Publier un mémoire", new_memoire_path, class: 'btn btn-default btn-lg', style: 'margin-top: 10px;' %>
            <%else%>
              <%= link_to "Publier un mémoire", new_user_session_path, class: 'btn btn-default btn-lg', style: 'margin-top: 10px;' %>
            <%end%>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%- if alert.present? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end -%>

<%- if notice.present? %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end -%>

<%- if flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:error] %>
  </div>
<% end -%>

<%- if flash[:success] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:success] %>
  </div>
<% end -%>

app/views/layouts/_search_header.html.erb
<div class="search-header-content">
  <div class="container">
    <div id="container">
      <div class="row">

        <div class="col-md-6 search-input col-md-offset-3">
          <h1 class="welcome-note-1" style="margin-bottom: 20px;">Filtrer selon vos besoins</h1>
          <%= form_tag recherche_path, :method => 'get', :class=> "form-margin" do %>
            <div class="input-group">
              <%= text_field_tag :search_parm, params[:search], placeholder: "Rechercher parmi plus de 1000 mémoires", :class=> "form-control search-control"%>
              <span class="input-group-btn search-control">
                <%= button_tag(type: "submit", class: "btn btn-prim search-control") do %>
                  <i class="fa fa-search" style="font-size: 28px;"></i>
                <% end %>
              </span>
            </div>
          <% end %>
          <!-- <div class="col-md-2 fb-container"></div> -->
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:url"           content="http://memoireapp.herokuapp.com" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Scuilt" />
  <meta property="og:description"   content="Une plateforme pour partager facilement vos memoires de soutenance avec vos proches." />
  <meta property="og:image"         content="https://s3-us-west-2.amazonaws.com/memoireapp/logo.png" />

  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'scuilt_cask.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
      <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
    <%= render 'layouts/footer' %>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.6&appId=819149694886677";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '819149694886677',
      cookie     : true,  // enable cookies to allow the server to access
                          // the session
      xfbml      : true,  // parse social plugins on this page
      version    : 'v2.5' // use graph api version 2.5
    });

    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  };

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-85394035-1', 'auto');
  ga('send', 'pageview');
</script>

</body>
</html>